### ISSUE TITLE
Plugin not working with Gradle 7

### ISSUE THREAD

**Issue by kjweinert** [HCL-TECH-SOFTWARE/appscan-source-gradle-plugin#23]
A very simple project using this plugin with Gradle 7 fails with the following error
Works fine in 6x. I assume this is just a Gradle change that will need to be addressed at some point

Error:
    Reason: A property without annotation isn't considered during up-to-date checking.
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

The command I ran was 
gradle createProject

My Gradle file.
plugins {
	id "com.ibm.appscan" version "1.1.9"
}
apply plugin: 'com.ibm.appscan'
appscansettings {
	server = "myASEserver.sample.com"
}
apply plugin: 'java'

**Comment by mattmurp** [comment]
This is fixed in version 1.1.10.
